import { lazy } from 'react'

export const AdminCategoriesPage = lazy(() => import('../features/admin/AdminCategoriesPage').then((module) => ({ default: module.AdminCategoriesPage })))
export const AdminDashboardPage = lazy(() => import('../features/admin/AdminDashboardPage').then((module) => ({ default: module.AdminDashboardPage })))
export const AdminItemsPage = lazy(() => import('../features/admin/AdminItemsPage').then((module) => ({ default: module.AdminItemsPage })))
export const AdminReviewPage = lazy(() => import('../features/admin/AdminReviewPage').then((module) => ({ default: module.AdminReviewPage })))
export const AdminUsersPage = lazy(() => import('../features/admin/AdminUsersPage').then((module) => ({ default: module.AdminUsersPage })))
export const ConversationDetailPage = lazy(() => import('../features/conversations/ConversationDetailPage').then((module) => ({ default: module.ConversationDetailPage })))
export const EditItemPage = lazy(() => import('../features/item-publish/EditItemPage').then((module) => ({ default: module.EditItemPage })))
export const FavoritesPage = lazy(() => import('../features/favorites/FavoritesPage').then((module) => ({ default: module.FavoritesPage })))
export const HomePage = lazy(() => import('../features/item-market/HomePage').then((module) => ({ default: module.HomePage })))
export const ItemDetailPage = lazy(() => import('../features/item-detail/ItemDetailPage').then((module) => ({ default: module.ItemDetailPage })))
export const ItemsPage = lazy(() => import('../features/item-market/ItemsPage').then((module) => ({ default: module.ItemsPage })))
export const LoginPage = lazy(() => import('../features/auth/LoginPage').then((module) => ({ default: module.LoginPage })))
export const MarketplacePlaceholderPage = lazy(() => import('../components/marketplace/MarketplacePlaceholderPage').then((module) => ({ default: module.MarketplacePlaceholderPage })))
export const MessagesPage = lazy(() => import('../features/conversations/MessagesPage').then((module) => ({ default: module.MessagesPage })))
export const MyItemsPage = lazy(() => import('../features/item-publish/MyItemsPage').then((module) => ({ default: module.MyItemsPage })))
export const OrdersPage = lazy(() => import('../features/orders/OrdersPage').then((module) => ({ default: module.OrdersPage })))
export const PlaceholderPage = lazy(() => import('../components/layout/PlaceholderPage').then((module) => ({ default: module.PlaceholderPage })))
export const ProfilePage = lazy(() => import('../features/profile/ProfilePage').then((module) => ({ default: module.ProfilePage })))
export const PublishPage = lazy(() => import('../features/item-publish/PublishPage').then((module) => ({ default: module.PublishPage })))
export const PurchaseDemandDetailPage = lazy(() => import('../features/orders/PurchaseDemandDetailPage').then((module) => ({ default: module.PurchaseDemandDetailPage })))
export const PurchaseDemandMinePage = lazy(() => import('../features/orders/PurchaseDemandMinePage').then((module) => ({ default: module.PurchaseDemandMinePage })))
export const PurchaseDemandNewPage = lazy(() => import('../features/orders/PurchaseDemandNewPage').then((module) => ({ default: module.PurchaseDemandNewPage })))
export const PurchaseDemandPage = lazy(() => import('../features/orders/PurchaseDemandPage').then((module) => ({ default: module.PurchaseDemandPage })))
export const VerifyPage = lazy(() => import('../features/profile/VerifyPage').then((module) => ({ default: module.VerifyPage })))
