import type { RouteMeta } from '../types/routes'

export const routeCatalog = [
  {
    path: '/login',
    title: '统一身份认证登录',
    permission: '公开',
    description: '对接厦门大学统一身份认证视觉入口，使用项目账号规则登录并自动建档。',
    guard: 'public',
    module: 'public',
    endpoints: ['POST /auth/login'],
  },
  {
    path: '/',
    title: '商品首页 / 推荐流',
    permission: '公开',
    description: '校园闲置商品推荐流，先覆盖教材、数码、宿舍用品、运动器材。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items',
    title: '商品搜索与分类筛选',
    permission: '公开',
    description: '支持关键词、分类、价格和取货方式筛选。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/textbook',
    title: '教材教辅分类',
    permission: '公开',
    description: '展示教材教辅分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/digital',
    title: '数码电子分类',
    permission: '公开',
    description: '展示数码电子分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/dorm',
    title: '宿舍用品分类',
    permission: '公开',
    description: '展示宿舍用品分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/outdoors',
    title: '运动户外分类',
    permission: '公开',
    description: '展示运动户外分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/daily-goods',
    title: '生活日用分类',
    permission: '公开',
    description: '展示生活日用分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/make-up',
    title: '美妆个护分类',
    permission: '公开',
    description: '展示美妆个护分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/instruments',
    title: '乐器文具分类',
    permission: '公开',
    description: '展示乐器文具分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/tickets',
    title: '票务转让分类',
    permission: '公开',
    description: '展示票务转让分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/others',
    title: '其他分类',
    permission: '公开',
    description: '展示其他分类下的校园闲置商品。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /items', 'GET /categories'],
  },
  {
    path: '/items/:id',
    title: '商品详情',
    permission: '公开，互动需登录',
    description: '商品详情公开浏览，收藏、私信和下单动作由登录态控制。',
    guard: 'interaction',
    module: 'public',
    endpoints: [
      'GET /items/{itemId}',
      'POST /items/{itemId}/favorite',
      'DELETE /items/{itemId}/favorite',
      'POST /conversations',
      'POST /orders',
    ],
  },
  {
    path: '/publish',
    title: '发布商品',
    permission: 'USER',
    description: '通过校园核验的用户发布闲置，提交后进入审核。',
    guard: 'verified',
    module: 'user',
    endpoints: ['POST /files/images', 'GET /categories', 'POST /items'],
  },
  {
    path: '/items/mine',
    title: '我的发布 / 上下架管理',
    permission: 'USER',
    description: '管理当前用户发布的商品状态和重新上架动作。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /users/me/items', 'POST /items/{itemId}/on-sale', 'POST /items/{itemId}/off-shelf'],
  },
  {
    path: '/items/:id/edit',
    title: '编辑商品',
    permission: '商品所有者',
    description: '仅商品所有者可编辑未售出且未违规下架的商品。',
    guard: 'owner',
    module: 'user',
    endpoints: ['GET /items/{itemId}', 'POST /files/images', 'GET /categories', 'PUT /items/{itemId}'],
  },
  {
    path: '/favorites',
    title: '我的收藏',
    permission: 'USER',
    description: '查看和取消收藏的商品。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /users/me/favorites', 'DELETE /items/{itemId}/favorite'],
  },
  {
    path: '/messages',
    title: '私信会话列表',
    permission: 'USER',
    description: '按商品聚合的交易沟通会话。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /conversations'],
  },
  {
    path: '/messages/:conversationId',
    title: '私信详情',
    permission: 'USER',
    description: '会话参与者查看和发送消息。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /conversations/{conversationId}/messages', 'POST /conversations/{conversationId}/messages'],
  },
  {
    path: '/orders',
    title: '购买订单入口',
    permission: 'USER',
    description: '兼容入口，重定向到 /orders/purchase。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /orders?role=BUYER', 'GET /orders/{orderId}', 'POST /orders/{orderId}/status'],
  },
  {
    path: '/orders/sales',
    title: '出售订单旧入口',
    permission: 'USER',
    description: '兼容入口，重定向到 /orders/sale。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /orders?role=SELLER', 'GET /orders/{orderId}', 'POST /orders/{orderId}/status'],
  },
  {
    path: '/orders/purchase',
    title: '购买订单',
    permission: 'USER',
    description: '查看买家侧订单进度，确认沟通、自提与完成状态。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /orders', 'GET /orders/{orderId}', 'POST /orders/{orderId}/status'],
  },
  {
    path: '/orders/sale',
    title: '出售订单',
    permission: 'USER',
    description: '查看卖家侧订单进度，联系买家并确认交易完成。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /orders', 'GET /orders/{orderId}', 'POST /orders/{orderId}/status'],
  },
  {
    path: '/orders/purchase/demand',
    title: '求购广场',
    permission: 'USER',
    description: '浏览校内求购需求，筛选预算、分类和匹配状态。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /demands', 'GET /conversations'],
  },
  {
    path: '/orders/purchase/demand/:id/detail',
    title: '求购详情',
    permission: 'USER',
    description: '查看单条求购的预算、成色、交易地点、发布者与匹配建议。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /demands/{demandId}', 'GET /demands/{demandId}/matches', 'GET /conversations'],
  },
  {
    path: '/orders/purchase/demand/new',
    title: '发布求购',
    permission: 'USER',
    description: '发布新的求购需求，填写预算、分类、取货方式和详细描述。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /categories', 'POST /demands'],
  },
  {
    path: '/orders/purchase/demand/mine',
    title: '我的求购 / 匹配结果',
    permission: 'USER',
    description: '维护自己发布的求购需求，并查看系统匹配到的商品。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /users/me/demands', 'GET /demands/{demandId}/matches', 'POST /demands/{demandId}/close'],
  },
  {
    path: '/demands',
    title: '求购列表',
    permission: '公开',
    description: '公开浏览校内求购需求。',
    guard: 'public',
    module: 'public',
    endpoints: ['GET /demands'],
  },
  {
    path: '/demands/new',
    title: '发布求购',
    permission: 'USER',
    description: '发布求购需求，后续由系统匹配对应商品。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /categories', 'POST /demands'],
  },
  {
    path: '/demands/mine',
    title: '我的求购 / 匹配结果',
    permission: 'USER',
    description: '维护自己的求购需求并查看匹配结果。',
    guard: 'verified',
    module: 'user',
    endpoints: ['GET /users/me/demands', 'GET /demands/{demandId}/matches', 'POST /demands/{demandId}/close'],
  },
  {
    path: '/profile',
    title: '个人信息 / 地址',
    permission: 'USER',
    description: '维护昵称、头像和校内收货地址。',
    guard: 'auth',
    module: 'user',
    endpoints: [
      'GET /auth/me',
      'PUT /users/me',
      'GET /users/me/addresses',
      'POST /users/me/addresses',
      'PUT /users/me/addresses/{addressId}',
      'DELETE /users/me/addresses/{addressId}',
    ],
  },
  {
    path: '/verify',
    title: '校园核验',
    permission: '登录用户',
    description: '提交实名、学号、学院和年级，用于校园身份核验。',
    guard: 'auth',
    module: 'user',
    endpoints: ['GET /auth/me', 'POST /auth/campus-verification'],
  },
  {
    path: '/admin',
    title: '后台数据看板',
    permission: 'ADMIN',
    description: '后台首页，展示发布量、成交统计、待审核数量和活跃用户。',
    guard: 'admin',
    module: 'admin',
    endpoints: ['GET /admin/dashboard/overview'],
  },
  {
    path: '/admin/items/review',
    title: '商品审核',
    permission: 'ADMIN',
    description: '审核待发布商品并记录审核意见。',
    guard: 'admin',
    module: 'admin',
    endpoints: ['GET /admin/items/review', 'POST /admin/items/{itemId}/review'],
  },
  {
    path: '/admin/items',
    title: '商品治理 / 违规下架',
    permission: 'ADMIN',
    description: '按状态、关键词、类目筛选全站商品并执行治理动作。',
    guard: 'admin',
    module: 'admin',
    endpoints: ['GET /admin/items', 'POST /admin/items/{itemId}/violation-remove'],
  },
  {
    path: '/admin/users',
    title: '用户与黑名单',
    permission: 'ADMIN',
    description: '查询用户核验状态并执行黑名单管理。',
    guard: 'admin',
    module: 'admin',
    endpoints: [
      'GET /admin/users',
      'POST /admin/users/{userId}/blacklist',
      'DELETE /admin/users/{userId}/blacklist',
    ],
  },
  {
    path: '/admin/categories',
    title: '类目管理',
    permission: 'ADMIN',
    description: '维护教材、数码、宿舍用品、运动器材等商品类目。',
    guard: 'admin',
    module: 'admin',
    endpoints: [
      'GET /admin/categories',
      'POST /admin/categories',
      'PUT /admin/categories/{categoryId}',
      'DELETE /admin/categories/{categoryId}',
    ],
  },
] satisfies RouteMeta[]
