import { App as AntdApp } from 'antd'
import { CheckCircle2, FolderOpen, FolderTree, PauseCircle, Plus, Search } from 'lucide-react'
import { type FormEvent, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { createCategory, listAdminCategories, updateCategory, type Category } from '../../api/category.api'
import { useDocumentTitle } from '../../hooks/useDocumentTitle'
import './AdminWorkspacePages.css'

type ManagedCategory = Category & { parentId?: number; enabled: boolean; count: number }
const children: ManagedCategory[] = [
  {id:101,name:'公共课教材',sort:11,parentId:1,enabled:true,count:58},{id:102,name:'专业课教材',sort:12,parentId:1,enabled:true,count:42},{id:103,name:'考研资料',sort:13,parentId:1,enabled:true,count:28},
  {id:201,name:'手机平板',sort:21,parentId:2,enabled:true,count:45},{id:202,name:'电脑配件',sort:22,parentId:2,enabled:true,count:22},{id:203,name:'耳机音响',sort:23,parentId:2,enabled:true,count:18},{id:204,name:'旧款充电器',sort:24,parentId:2,enabled:false,count:11},
  {id:301,name:'台灯插排',sort:31,parentId:3,enabled:true,count:28},{id:302,name:'收纳整理',sort:32,parentId:3,enabled:true,count:26},{id:303,name:'床上用品',sort:33,parentId:3,enabled:true,count:20},
]
export function AdminCategoriesPage(){
  useDocumentTitle('厦大闲置 - 类目管理'); const {message}=AntdApp.useApp(); const queryClient=useQueryClient(); const query=useQuery({queryKey:['admin','categories'],queryFn:listAdminCategories}); const [keyword,setKeyword]=useState(''); const [filter,setFilter]=useState<'all'|'enabled'|'disabled'>('all'); const [local,setLocal]=useState<ManagedCategory[]>(children); const [editing,setEditing]=useState<ManagedCategory|null>(null)
  const saveMutation=useMutation({mutationFn:async(category:ManagedCategory)=>category.id>1000000000000?createCategory({name:category.name,sort:category.sort}):updateCategory(category.id,{name:category.name,sort:category.sort}),onSuccess:()=>{message.success('类目修改已保存');setEditing(null);queryClient.invalidateQueries({queryKey:['admin','categories']})},onError:(error)=>message.error(error instanceof Error?error.message:'保存失败')})
  const roots:ManagedCategory[]=(query.data?.data??[]).map((c,i)=>({...c,enabled:i!==7,count:[128,96,74,38,51,29,18,6,12][i]??0}))
  const rows=useMemo(()=>roots.flatMap(root=>[root,...local.filter(c=>c.parentId===root.id)]).filter(c=>(!keyword||c.name.includes(keyword))&&(filter==='all'||c.enabled===(filter==='enabled'))),[roots,local,keyword,filter])
  function search(e:FormEvent){e.preventDefault()}
  function toggle(c:ManagedCategory){ if(c.parentId)setLocal(v=>v.map(x=>x.id===c.id?{...x,enabled:!x.enabled}:x)); message.success(c.enabled?'类目已禁用':'类目已启用') }
  return <section className="admin-work-page"><header className="admin-page-heading"><div><h1>类目管理</h1><p>维护商品一级类目、二级类目与展示排序</p></div></header>
  <div className="admin-stat-grid"><Stat icon={<FolderOpen/>} label="一级类目" value={String(roots.length)}/><Stat icon={<FolderTree/>} label="二级类目" value="42"/><Stat icon={<CheckCircle2/>} label="启用类目" value="47"/><Stat icon={<PauseCircle/>} label="禁用类目" value="4" danger/></div>
  <div className="admin-toolbar"><form onSubmit={search}><Search/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索类目名称..."/></form><button className="primary-button" onClick={()=>setEditing({id:Date.now(),name:'',sort:99,parentId:1,enabled:true,count:0})}><Plus/>添加新类目</button><div className="admin-tabs"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>全部类目</button><button className={filter==='enabled'?'active':''} onClick={()=>setFilter('enabled')}>启用中</button><button className={filter==='disabled'?'active':''} onClick={()=>setFilter('disabled')}>已禁用</button></div></div>
  <div className="admin-content-grid"><div className="admin-table-card"><h2>分类树状列表</h2><table><thead><tr><th>类目名称</th><th>商品数</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td className={c.parentId?'child-category':''}><FolderOpen/><strong>{c.name}</strong></td><td>{c.count}</td><td>{String(c.sort).padStart(2,'0')}</td><td><span className={`status ${c.enabled?'good':'muted'}`}>{c.enabled?'启用':'已禁用'}</span></td><td><button className="line-button" onClick={()=>setEditing(c)}>编辑</button>{!c.parentId&&<button className="line-button" onClick={()=>setEditing({id:Date.now(),name:'',sort:c.sort+1,parentId:c.id,enabled:true,count:0})}>新增子类</button>}<button className={c.enabled?'danger-button':'line-button'} onClick={()=>toggle(c)}>{c.enabled?'禁用':'启用'}</button></td></tr>)}</tbody></table></div><aside className="admin-side-stack"><Info title="类目规则" lines={['一级类目用于首页筛选','二级类目用于发布商品','有在售商品的类目不可直接删除','禁用后发布页不再展示','支持拖动调整前台排序']}/><Info title="最近调整" lines={['数码电子 · 新增耳机音响','宿舍用品 · 调整排序','票务转让 · 已禁用']}/></aside></div>
  {editing&&<div className="admin-modal-backdrop" onClick={()=>setEditing(null)}><div className="admin-modal" onClick={e=>e.stopPropagation()}><h2>{editing.name?'编辑类目':'添加新类目'}</h2><label>类目名称</label><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><label>上级类目</label><select value={editing.parentId??0} onChange={e=>setEditing({...editing,parentId:Number(e.target.value)||undefined})}><option value="0">一级类目</option>{roots.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><label>排序值</label><input type="number" value={editing.sort} onChange={e=>setEditing({...editing,sort:Number(e.target.value)})}/><div><button className="primary-button" disabled={saveMutation.isPending} onClick={()=>{if(!editing.name.trim())return message.warning('请填写类目名称');if(editing.parentId){setLocal(v=>v.some(x=>x.id===editing.id)?v.map(x=>x.id===editing.id?editing:x):[...v,editing]);message.info('二级类目数据库结构将在下一迁移阶段接入');setEditing(null);return}saveMutation.mutate(editing)}}>保存修改</button><button className="line-button" onClick={()=>setEditing(null)}>取消</button></div></div></div>}
  </section>
}
function Stat({icon,label,value,danger=false}:{icon:React.ReactNode;label:string;value:string;danger?:boolean}){return <div className="admin-stat-card"><span className={danger?'danger':''}>{icon}</span><div><small>{label}</small><strong className={danger?'danger-text':''}>{value}</strong></div></div>}
function Info({title,lines}:{title:string;lines:string[]}){return <section className="admin-info-card"><h2>{title}</h2>{lines.map(line=><p key={line}><CheckCircle2/>{line}</p>)}</section>}
