create table if not exists users (
	id bigint generated by default as identity primary key,
	phone varchar(20) not null unique,
	nickname varchar(40) not null,
	avatar_url varchar(500),
	role varchar(20) not null,
	verification_status varchar(30) not null,
	real_name varchar(40),
	student_no varchar(32) unique,
	college varchar(80),
	grade varchar(20),
	blacklist_reason varchar(255),
	blacklist_expire_at timestamp with time zone,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);
