create table if not exists users (
	id bigint generated by default as identity primary key,
	phone varchar(20) not null unique,
	nickname varchar(40) not null,
	avatar_url varchar(500),
	role varchar(20) not null,
	verification_status varchar(30) not null,
	real_name varchar(40),
	student_no varchar(32) unique,
	college varchar(80),
	grade varchar(20),
	blacklist_reason varchar(255),
	blacklist_expire_at timestamp with time zone,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table if not exists user_addresses (
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	receiver_name varchar(40) not null,
	receiver_phone varchar(20) not null,
	campus_area varchar(80) not null,
	detail varchar(255) not null,
	default_address boolean not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table if not exists categories (
	id bigint generated by default as identity primary key,
	name varchar(40) not null unique,
	sort integer not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);
