create table if not exists users (
	id bigint generated by default as identity primary key,
	phone varchar(20) not null unique,
	nickname varchar(40) not null,
	avatar_url varchar(500),
	role varchar(20) not null,
	verification_status varchar(30) not null,
	real_name varchar(40),
	student_no varchar(32) unique,
	college varchar(80),
	grade varchar(20),
	blacklist_reason varchar(255),
	blacklist_expire_at timestamp with time zone,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table if not exists user_addresses (
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	receiver_name varchar(40) not null,
	receiver_phone varchar(20) not null,
	campus_area varchar(80) not null,
	detail varchar(255) not null,
	default_address boolean not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table if not exists categories (
	id bigint generated by default as identity primary key,
	name varchar(40) not null unique,
	sort integer not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table if not exists items (
	id bigint generated by default as identity primary key,
	seller_id bigint not null,
	title varchar(80) not null,
	description varchar(2000) not null,
	category_id bigint not null,
	price_cent bigint not null,
	status varchar(30) not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);

create table if not exists item_delivery_modes (
	item_id bigint not null,
	delivery_mode varchar(40) not null
);

create table if not exists item_images (
	item_id bigint not null,
	sort_order integer not null,
	image_url varchar(500) not null
);

create table if not exists audit_logs (
	id bigint generated by default as identity primary key,
	actor_user_id bigint not null,
	target_type varchar(40) not null,
	target_id bigint not null,
	action varchar(80) not null,
	remark varchar(255),
	created_at timestamp with time zone not null
);

create table if not exists favorites (
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	item_id bigint not null,
	created_at timestamp with time zone not null,
	constraint uk_favorites_user_item unique (user_id, item_id)
);

create table if not exists trade_orders (
	id bigint generated by default as identity primary key,
	item_id bigint not null,
	buyer_id bigint not null,
	seller_id bigint not null,
	delivery_mode varchar(40) not null,
	remark varchar(255),
	status varchar(40) not null,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null
);
